name: Github Page

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: Set Environment Variables
        env:
          BASE_PATH: /react-texteditor-example
        run: |
          echo "" > ./src/env.js
          echo BASE_PATH=$BASE_PATH >> ./src/env.js
      - name: Build
        run: pnpm run build
      - name: Create .nojekyll
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: SeaUrc/SeaUrc.github.io
        with:
          folder: out